title: "Mamadou THIAM"
email: "mamadouth2025@gmail.com"
description: "Portfolio - DÃ©veloppeur Web & Data"
baseurl: ""
url: "https://mamadou-thiam-dev.github.io"

social:
  github: "https://github.com/mamadou-thiam-dev"
  email: "mailto:mamadouth2025@gmail.com"
